experiments:
  - name: "experiment_1"
    base_dir: "/kaggle/working/data"
    seed: 1
    device: "auto"

    data:
      label_split_ratio: 0.1
      test_split_ratio: 0.2
      augment: true

    training:
      dropout: 0.3
      batch_size: 16
      lr: 0.001
      patience: 15
      min_delta: 0.0001

    active_learning:
      sample_size: 2
      mc_runs: 8
      loop_iterations: null    # set to null to disable
      acquisition_functions:
        - js-divergence
        - kl-divergence
        - entropy
        - taal-unweighted
        - taal

    ssl:
      ssl_lambda_max: 1.0
      ssl_ramp_epochs: 10

    output:
      results_dir: "/kaggle/working/results"
      log_format: "{method}_log.csv"
